version: "3.3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=20a1ad25f38e376a3725
      - ACCEPT_EULA=Y
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"
    volumes:
      - volume-sqlserver:/var/opt/mssql/data
      - volume-sqlserver:/var/opt/mssql/log
      - volume-sqlserver:/var/opt/mssql/secrets
    restart: always
    networks:
      - rede-sqlserver

volumes:
  volume-sqlserver:

networks:
  rede-sqlserver:
    driver: bridge
