version: "3.3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "<Crie uma Senha Forte>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - volume-sqlserver:/var/opt/mssql/data
      - volume-sqlserver:/var/opt/mssql/log
      - volume-sqlserver:/var/opt/mssql/secrets
    restart: always

volumes:
  volume-sqlserver:
    external: true
