version: "3.3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=20a1ad25f38e376a3725
      - ACCEPT_EULA=Y
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"
    volumes:
      - ./volumes/sqlserver/sqlserver_data:/var/opt/mssql/data
      - ./volumes/sqlserver/sqlserver_log:/var/opt/mssql/log
      - ./volumes/sqlserver/sqlserver_secrets:/var/opt/mssql/secrets
    restart: always
    networks:
      - rede-sqlserver

networks:
  rede-sqlserver:
    driver: bridge
